name: Validate Base Bridge Address
on:
  pull_request:
    paths:
      - "apps/bridge/assets.ts"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"

      - name: Install npm dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Run Compiled Validation Script
        run: node dist/baseBridgeAddress.js
